{
  try {
    condition.await();
  }
 catch (  InterruptedException e) {
    throw new AssertionError(e);
  }
}
