def clientSetupFailed(self, reason):
    self._errback(reason)
