def test_bad_calls(self):
    _expect_exception((lambda : client.insert('Table1', 'key1', ColumnPath('Standard1', 'x', 'y'), 'value', 0, ConsistencyLevel.ONE)), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', ColumnPath('Standard1'), ConsistencyLevel.ONE)), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', ColumnPath('Standard1', 'x', 'y'), ConsistencyLevel.ONE)), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', ColumnPath('Super1'), ConsistencyLevel.ONE)), InvalidRequestException)
    _expect_exception((lambda : client.get_column('Table1', 'key1', ColumnPath('Super1', 'x'), ConsistencyLevel.ONE)), InvalidRequestException)
    _expect_exception((lambda : client.get_key_range('Table1', 'S', '', '', 1000)), InvalidRequestException)
