{
  try {
    return iterator.hasNext();
  }
 catch (  IOError e) {
    if (e.getCause() != null && e.getCause() instanceof IOException) {
      exception=(IOException)e.getCause();
      return false;
    }
    throw e;
  }
}
