def assert_raises(exception, method, *args, **kwargs):
    try:
        method(*args, **kwargs)
    except exception:
        return
    raise AssertionError('failed to see expected exception')
