{
  try {
    tests.verify();
    fail("Expected a startup exception but none was thrown");
  }
 catch (  StartupException e) {
    assertTrue(e.getMessage().contains(message));
  }
}
